### ISSUE TITLE
How can i use kademlia behind a NAT?

### ISSUE THREAD

**Issue by An0nB0y** [bmuller/kademlia#100]
Hello, (again)
I saw an Issue earlier about how kademlia works behind NAT. And, i didn't find any module for that. That's one.
Two, i think you didn't understand my last issue. I meant, how can i read the IP addresses list. When i run the scripts, i just see the output of the kademlia.crawling but i need to use this output in further scripts.
I'm sorry for all those questions. Thanks in advance!

**Comment by bmuller** [comment]
@An0nB0y github issues is used exclusively for reporting bugs and issues - if you have any general questions about the library please email the address shown on my github profile page.

> I saw an Issue earlier about how kademlia works behind NAT. And, i didn't find any module for that. 

Because the lib uses [RPC over UDP](https://github.com/bmuller/rpcudp), it is possible to have a node behind a NAT due to UDP holepunching.

> Two, i think you didn't understand my last issue. I meant, how can i read the IP addresses list. When i run the scripts, i just see the output of the kademlia.crawling but i need to use this output in further scripts.

If you need to get the IP's of all of the other nodes that your node knows about, you can iterate over your node's `self.protocol.router.buckets` which each contain lists of nodes that each contain an `ip` property.
