### ISSUE TITLE
any example to find and download files in kademlia?

### ISSUE THREAD

**Issue by niceday345** [bmuller/kademlia#101]
I want to build a website that search and download files in kad network, like search files in emule, but I almost know nothing about kad.
I need some code examples that find and download files in kad.

**Comment by bmuller** [comment]
Hey @niceday345 - this library is likely too lowlevel for what you're looking for (it stores binary blobs with a max size, you'd have to break a file apart into a merkle tree etc yourself if you want to store files).  I recommend looking at IPFS.

**Comment by thiswillbeyourgithub** [comment]
Hi @bmuller 

I too am interested in way to store files in a p2p way using your library and I don't mind your lib being low level as it does not look hard to build a minimal abstraction to exchange files.

I do have a question though: what are the constraints on the keys and values (number, length, format, etc, ...)?

Also, I don't see why we'd need merkle trees. I can think of simpler other ways. Say I have to split a 1G file into N chunks. I can just hash the file, then recursively hash that hash N times so that I have N unique hashes. Then I can store each i'th chunk as value to the i'th hash. Hence I just have to give the hash of the file to someone else and they'll be able to recover all the keys for all the chunks in the right order. To get verifiabillity we can add an intermediate hash: the i'th hash is now a key that leads to another hash which is both the hash of the i'th chunk and the key to the actual chunk. This way the end user can check if each chunk is valid. Also the receiver needs to know how many chunks there are to retrieve so we can just store that number as value to that hash. Is that dumb and am I just reinventing the wheel here?

**Comment by bmuller** [comment]
@thiswillbeyourgithub  - This lib uses rpcudp which limits messages to a reasonable MTU of 8k - meaning you can't store any values greater than 8k in a single value.

If you want to store files in a p2p way, this is most likely *not* the library you're looking for (again, too low level).  What you've described is basically IPFS (which uses a DHT under the hood, but abstracts things like splitting/reassembling file chunks, merkle trees, etc), which is what you should most likely be using instead.

**Comment by thiswillbeyourgithub** [comment]
Thanks a lot for the quick answer.

**Comment by thiswillbeyourgithub** [comment]
And for anyone else wondering, the library [py_ipfs_node](https://github.com/emendir/py_ipfs_node) seems to provide the appropriate elements for exchanging files directly in python.

**Comment by thiswillbeyourgithub** [comment]
> And for anyone else wondering, the library [py_ipfs_node](https://github.com/emendir/py_ipfs_node) seems to provide the appropriate elements for exchanging files directly in python.

Even better: dead simple p2p packet exchange via [prime-iroh](https://github.com/PrimeIntellect-ai/prime-iroh/blob/main/python/examples/bidirectional.py).
