### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by memwey** [bmuller/kademlia#23]
- There is a problem that the max value of the C{KBucket}.depth() return is 20(which is the length return by util.sharedPrefix()). So I think the ids of the nodes are compared in the form of bytes but not bits. I fixed this problem in a ugly way, turning bytes into integer and then bin() and then add some 0 in the head, so I won't pull my code to you. : D
- There will be a problem that, for example, when a KBucket for the prefix 1111 is full of nodes with prefix 11111, this KBucket can never split however it should if a node with 11110 comes in. So I think the new come node should be determine the KBucket to be split or not. This can be done to pass the new come node's id into C{KBucket}.depth().
- In the original paper, the author suggest that drop the node only if it hasn't responded for 5 times, in the case that udp is unreliable. I notice that in your implementation the node is removed as long as it have not responded once. In my simulation the network can hardly be stable. May I ask why do you do so?

**Comment by bmuller** [comment]
Hey @Eloahman - thanks for the continued help!

I think the first issue is fixed in [this commit](https://github.com/bmuller/kademlia/commit/125abe7415b65ca68e7812544d7c4064ffeeacdf).

For the second issue, I'm not sure I understand.  The determination about whether to split or not is entirely dependent on the depth of the bucket *before* adding the new node.

For the third issue, you're right, the last part of section 4.1 of the paper has not been implemented.  This was merely due to the added complexity of adding locking / attempt counts / etc.  I'll happily accept a patch, though, if you'd like to add it!

Feel free to create separate issues for each item in the future (so they can be closed one by one).  Thanks for the help!

**Comment by Eloahman** [comment]
Thanks for your guidance in how to use issues. I'm sorry that  I'm new to github and know little about the principle.

For the second issue, in my opinion, the bucket should split depending on the bit space itself but not the ids of the node in it. It's a bit hard to explain but I will try.
Let the bucket for the prefix x be bucket[x].
bucket[1011] contains nodes whose id is 1011*
Take the node whose node.id is all 0 as an example. After the first split, it will have two buckets in it. bucket[0] contains the node whose id starts with 0 and the bucket[1] contains the nodes with 1. And the second bucket will go on split into bucket[10] and the bucket[11] and go on split. It finally forms 16 buckets for the five prefix 1{0,1}{0,1}{0,1}{0,1}, since in the paper it mods 5.
The problem in the code is on how to determine the split. If, unluckily, after the first split, the bucket[1] is full of node whose id starts 11111. When a node whose id is 10* comes in, it should split into bucket[10] and bucket[11] but it won't. Its self.depth() returns 5 because the nodes in it all share a prefix of 11111. In fact, if so, the bucket can never split again.

        # Per section 4.2 of paper, split if the bucket has the node in its range
        # or if the depth is not congruent to 0 mod 5
        if bucket.hasInRange(self.node) or bucket.depth() % 5 != 0:
            self.splitBucket(index)
            self.addContact(node)
        else:
            asyncio.ensure_future(self.protocol.callPing(bucket.head()))


    def depth(self):
        sp = sharedPrefix([bytesToBitString(n.id) for n in self.nodes.values()])
        return len(sp)

**Comment by bmuller** [comment]
I'm still not sure I understand what you're suggesting.  For your example, I think you should give actual ID's (and specify the bucket ID ranges) so it makes sense in the context of the existing code.  Better yet, providing an example script that uses KBucket and the router and demonstrates the issue would be even better.

**Comment by Talon001** [comment]
it is not support python3?

**Comment by bmuller** [comment]
Hey @Talon001 - please see the python3.5 branch.  If you have any other questions, please feel free to email me at the address on my profile (this comments section is for specific issues rather than general questions).

**Comment by Talon001** [comment]
Thank you very much, bmuller.
I am a newcomer, just want to fine some project to learn and code something. 
First i wanna code a pogram like the emule(only useing kademlia no severs) ,and it powered by python ,maybe i must learn this much time first,i wish i can.
Thank you. sorry for my poor english.

**Comment by bmuller** [comment]
Gonna close this out.  @memwey feel free to reopen if you have any additional clarification/issues.  Thanks!
