### ISSUE TITLE
K closest neighbours

### ISSUE THREAD

**Issue by bladechen** [bmuller/kademlia#28]
Hi Bmuller,

According to the paper, find_node should return the most closest nodes in its routing table.
I think the code may have bug, firstly it should reversed pop the right bucket, moreover, the node in the same bucket not sorted by distances.

Correct me if I made a mistake
thanks

`   

    def next(self):
        """
        Pop an item from the left subtree, then right, then left, etc.
        """
        if len(self.currentNodes) > 0:
            return self.currentNodes.pop()

        if self.left and len(self.leftBuckets) > 0:
            self.currentNodes = self.leftBuckets.pop().getNodes()
            self.left = False
            return self.next()

        if len(self.rightBuckets) > 0:
            self.currentNodes = self.rightBuckets.pop().getNodes()
            self.left = True
            return self.next()

        raise StopIteration
`

 `   

     def findNeighbors(self, node, k=None, exclude=None):
        k = k or self.ksize
        nodes = []
        for neighbor in TableTraverser(self, node):
            if neighbor.id != node.id and (exclude is None or not neighbor.sameHomeAs(exclude)):
                heapq.heappush(nodes, (node.distanceTo(neighbor), neighbor))
            if len(nodes) == k: // should be commented
                break // should be commented

        return map(operator.itemgetter(1), heapq.nsmallest(k, nodes))
`

**Comment by CynthiaTong** [comment]
Agreed, alternate popping from left and right buckets does not return the strictly closest nodes. See [this](https://stackoverflow.com/questions/30654398/implementing-find-node-on-torrent-kademlia-routing-table) stackoverflow post. The simplest way to find k closest nodes seems to be scanning through the whole routing table.

**Comment by bladechen** [comment]
yes, the simple way to achieve that is scan whole table, but it can be optimized by scanning iteratively left & right(all nodes in that bucket should be included, it may exceed K), then pick K nodes with minimum distance.
 I am still stuck in the implementation of Kademlia,

**Comment by bmuller** [comment]
Thanks @bladechen.  The paper is a bit ambiguous on the `find_node` function because it mentions just returning all of the closest nodes in a single k-bucket, and only looking to other k-buckets in the case that the closest k-bucket isn't full (see section 2.3 second paragraph).  The one implication for making the changes you suggest would be that you would no longer preferentially be returning least-recently-seen nodes, though I'm not sure if that would be bad at all.  At first glance it seems that returning the closest nodes would be the most immediate optimal solution (and would fall in line with the first 2 sentences talking about the function `find_node`).  I'd be happy to take a look at a pull request.

Thanks!

**Comment by CynthiaTong** [comment]
Emm @bladechen, from what I understand it still won't do, since the _xor distance_ (not integer distance) is not guaranteed to be closer in nearby buckets. This is of course assuming that you want the closest nodes in the strict sense, which is not clearly indicated in the paper as @bmuller has suggested.

**Comment by sivanagarajumolabant** [comment]
@bladechen i need your help can please give me your emailid
