### ISSUE TITLE
IPv4-only node communicating with dual stack node

### ISSUE THREAD

**Issue by Edraens** [bmuller/kademlia#81]
Hi,
Firstly, I'm using your lib in a study project and I find it truly amazing. Thank you for this.
There is something I couldn't figure out - I'm sorry if it's the wrong place to ask.
I have three nodes, one of them being used by the two others to bootstrap. All nodes are IPv6/IPv4 enabled and listening to 0.0.0.0 and "::", except one of them which is IPv4 only (this is not the node used for bootstrap).

When the dual stack one bootstraps against the bootstrap node, it uses his IPv6 address as source. I'm assuming that his IPv4 is then not stored in the bootstrap node neighbors list (maybe I'm wrong)
Then, when the IPv4-only node bootstraps against bootstrap node, will it be able to set or get data from the dual stack node ? Will the bootstrap node sends him the dual stack node IPv4 even if it used his IPv6 to bootstrap ?

I hope this does not look too confused. It's working perfectly when all the nodes are dual stack capable, but I want to ensure that if a node cannot have IPv6 connectivity it will be able to fully act like every other one.
Thank you

**Comment by bmuller** [comment]
The nodes should share the IP/port combo with other nodes based on whatever they saw on the initial connection.  Otherwise, it'll look like a different node.  So if node 1 knows about the IPv4 interface of node 2 and then finds about about the IPv6 interface for node 2, it'll think that's a new node.  In general, there can't really be much interoperability between nodes on both networks (split brain problem) unless most of the nodes have dual interfaces.
